### PR TITLE
Vinai/branches UI changes

### LINKED ISSUE #34: New PRs from a branch should populate that branch as 'Source Branch'
When user is working on a branch that has diffs, the 'Add a new pull request' screen should default to using that branch as the 'Source Branch'.

In the example below, I'm on the `atl-augment` branch.  When I create a PR, the Source Branch should auto-populate with `atl-augment`.

image

### LINKED ISSUE #43: add column in branch table to show "active" status
keep green "Active" but make label and should be in column 2

### LINKED ISSUE #44: replace Merge button with PR button in branch table

### LINKED ISSUE #45: add "Catch up" button to branch table redirecting to PR page

### LINKED ISSUE #46: replace "checkout" with "Activate" button in branch table

### PR DESCRIPTION
**Pull request by VinaiRachakonda**
Add the following UI changes

1. Active column
2. Checkout -> activate
3. Pr/Catchup buttons

### CODE REVIEW

**Comment by VinaiRachakonda** [comment]
image

**Comment by VinaiRachakonda** [comment]
image

**Comment by VinaiRachakonda** [comment]
Screen Shot 2021-09-09 at 9 27 41 AM

**Comment by andrew-wm-arthur** [comment]
Per Jason, change "Active" column name to "Status"

**Comment by andrew-wm-arthur** [comment]
Remove "activate" button from "active" branch

**Comment by VinaiRachakonda** [comment]
Screen Shot 2021-09-10 at 11 37 24 AM

**Pull request merged**
