### PR TITLE
Update to the latest versions of nautobot and dolt.

### PR DESCRIPTION
**Pull request by PavelSafronov**
Fixed a number of issues that were breaking tests or functionality:
- missing "slug" in development/db.json
- updated dolt calls to use stored procs instead of attempting to update a read-only table
- Branch QuerySet deletes are disabled, Branch objects need to be deleted individually (Django QuerySet delete behavior bypasses model delete method and tries to remove items from a read-only table)
- minor test updates
- added some test cleanup logic

Minor additions:
- unittest can now accept `debug` flag, which will results in queries being logged

Testing done:
- `inv destroy && inv build && inv unittest` passes without issues
- `inv destroy && inv build && inv migrate && inv load-data && inv start` succeeds, local Nautobot can be reached at http://0.0.0.0:8080/, branches and PRs can be created using the version control plugin

### CODE REVIEW

**Comment by PavelSafronov** [comment]
Question for maintainers: I'm currently seeing flake8 errors in files that I haven't touched. Is that expected?

**Comment by itdependsnetworks** [comment]
I think you can ignore for now, I'll try and get the repo back into shape with our standards and similar.

**Comment by PavelSafronov** [comment]
The PR has been updated to use the latest version of Nautobot, 1.5.16.
You can find the current PR hosted at [http://18.236.91.77:8080](http://18.236.91.77:8080/), it is running against [hosted dolt](https://hosted.doltdb.com/). The hosted dolt DB is not public, but I can share access to it if anyone is interested.

**Comment by itdependsnetworks** [comment]
I changed base, going to push to next and update the environment, once that is done, will get merge back into develop/main and release

**Pull request merged**
